# Generated by Django 5.0.7 on 2024-07-25 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0002_alter_bme280_altitude_alter_bme280_humidity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='sen5x',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_id', models.IntegerField(blank=True, null=True)),
                ('sensor_type', models.CharField(blank=True, max_length=255)),
                ('location', models.IntegerField(blank=True, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('P1', models.FloatField(blank=True, null=True)),
                ('P4', models.FloatField(blank=True, null=True)),
                ('P2', models.FloatField(blank=True, null=True)),
                ('P0', models.FloatField(blank=True, null=True)),
                ('N10', models.FloatField(blank=True, null=True)),
                ('N4', models.FloatField(blank=True, null=True)),
                ('N25', models.FloatField(blank=True, null=True)),
                ('N1', models.FloatField(blank=True, null=True)),
                ('N05', models.FloatField(blank=True, null=True)),
                ('TS', models.FloatField(blank=True, null=True)),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('humidity', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='sht10',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_id', models.IntegerField(blank=True, null=True)),
                ('sensor_type', models.CharField(blank=True, max_length=255)),
                ('location', models.IntegerField(blank=True, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('humidity', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
