# Generated by Django 5.1.6 on 2025-03-21 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="bme280",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sensor_id", models.IntegerField(blank=True, null=True)),
                ("sensor_type", models.CharField(blank=True, max_length=255)),
                ("location", models.IntegerField(blank=True, null=True)),
                ("lat", models.FloatField(blank=True, null=True)),
                ("lon", models.FloatField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(blank=True, null=True)),
                ("pressure", models.FloatField(blank=True, null=True)),
                ("altitude", models.FloatField(blank=True, null=True)),
                ("pressure_sealevel", models.FloatField(blank=True, null=True)),
                ("temperature", models.FloatField(blank=True, null=True)),
                ("humidity", models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="bmp180",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sensor_id", models.IntegerField(blank=True, null=True)),
                ("sensor_type", models.CharField(blank=True, max_length=255)),
                ("location", models.IntegerField(blank=True, null=True)),
                ("lat", models.FloatField(blank=True, null=True)),
                ("lon", models.FloatField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(blank=True, null=True)),
                ("pressure", models.FloatField(blank=True, null=True)),
                ("altitude", models.FloatField(blank=True, null=True)),
                ("pressure_sealevel", models.FloatField(blank=True, null=True)),
                ("temperature", models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="bmp280",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sensor_id", models.IntegerField(blank=True, null=True)),
                ("sensor_type", models.CharField(blank=True, max_length=255)),
                ("location", models.IntegerField(blank=True, null=True)),
                ("lat", models.FloatField(blank=True, null=True)),
                ("lon", models.FloatField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(blank=True, null=True)),
                ("pressure", models.FloatField(blank=True, null=True)),
                ("altitude", models.FloatField(blank=True, null=True)),
                ("pressure_sealevel", models.FloatField(blank=True, null=True)),
                ("temperature", models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="dht22",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sensor_id", models.IntegerField(blank=True, null=True)),
                ("sensor_type", models.CharField(blank=True, max_length=255)),
                ("location", models.IntegerField(blank=True, null=True)),
                ("lat", models.FloatField(blank=True, null=True)),
                ("lon", models.FloatField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(blank=True, null=True)),
                ("temperature", models.FloatField(blank=True, null=True)),
                ("humidity", models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ds18b20",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sensor_id", models.IntegerField(blank=True, null=True)),
                ("sensor_type", models.CharField(blank=True, max_length=255)),
                ("location", models.IntegerField(blank=True, null=True)),
                ("lat", models.FloatField(blank=True, null=True)),
                ("lon", models.FloatField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(blank=True, null=True)),
                ("temperature", models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="hpm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sensor_id", models.IntegerField(blank=True, null=True)),
                ("sensor_type", models.CharField(blank=True, max_length=255)),
                ("location", models.IntegerField(blank=True, null=True)),
                ("lat", models.FloatField(blank=True, null=True)),
                ("lon", models.FloatField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(blank=True, null=True)),
                ("P1", models.FloatField(blank=True, null=True)),
                ("P2", models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="htu21d",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sensor_id", models.IntegerField(blank=True, null=True)),
                ("sensor_type", models.CharField(blank=True, max_length=255)),
                ("location", models.IntegerField(blank=True, null=True)),
                ("lat", models.FloatField(blank=True, null=True)),
                ("lon", models.FloatField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(blank=True, null=True)),
                ("temperature", models.FloatField(blank=True, null=True)),
                ("humidity", models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="pms1003",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sensor_id", models.IntegerField(blank=True, null=True)),
                ("sensor_type", models.CharField(blank=True, max_length=255)),
                ("location", models.IntegerField(blank=True, null=True)),
                ("lat", models.FloatField(blank=True, null=True)),
                ("lon", models.FloatField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(blank=True, null=True)),
                ("P1", models.FloatField(blank=True, null=True)),
                ("P2", models.FloatField(blank=True, null=True)),
                ("P0", models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="pms3003",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sensor_id", models.IntegerField(blank=True, null=True)),
                ("sensor_type", models.CharField(blank=True, max_length=255)),
                ("location", models.IntegerField(blank=True, null=True)),
                ("lat", models.FloatField(blank=True, null=True)),
                ("lon", models.FloatField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(blank=True, null=True)),
                ("P1", models.FloatField(blank=True, null=True)),
                ("P2", models.FloatField(blank=True, null=True)),
                ("P0", models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="pms5003",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sensor_id", models.IntegerField(blank=True, null=True)),
                ("sensor_type", models.CharField(blank=True, max_length=255)),
                ("location", models.IntegerField(blank=True, null=True)),
                ("lat", models.FloatField(blank=True, null=True)),
                ("lon", models.FloatField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(blank=True, null=True)),
                ("P1", models.FloatField(blank=True, null=True)),
                ("P2", models.FloatField(blank=True, null=True)),
                ("P0", models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="pms6003",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sensor_id", models.IntegerField(blank=True, null=True)),
                ("sensor_type", models.CharField(blank=True, max_length=255)),
                ("location", models.IntegerField(blank=True, null=True)),
                ("lat", models.FloatField(blank=True, null=True)),
                ("lon", models.FloatField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(blank=True, null=True)),
                ("P1", models.FloatField(blank=True, null=True)),
                ("P2", models.FloatField(blank=True, null=True)),
                ("P0", models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="pms7003",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sensor_id", models.IntegerField(blank=True, null=True)),
                ("sensor_type", models.CharField(blank=True, max_length=255)),
                ("location", models.IntegerField(blank=True, null=True)),
                ("lat", models.FloatField(blank=True, null=True)),
                ("lon", models.FloatField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(blank=True, null=True)),
                ("P1", models.FloatField(blank=True, null=True)),
                ("P2", models.FloatField(blank=True, null=True)),
                ("P0", models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ppd42ns",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sensor_id", models.IntegerField(blank=True, null=True)),
                ("sensor_type", models.CharField(blank=True, max_length=255)),
                ("location", models.IntegerField(blank=True, null=True)),
                ("lat", models.FloatField(blank=True, null=True)),
                ("lon", models.FloatField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(blank=True, null=True)),
                ("P1", models.FloatField(blank=True, null=True)),
                ("durP1", models.FloatField(blank=True, null=True)),
                ("ratioP1", models.FloatField(blank=True, null=True)),
                ("P2", models.FloatField(blank=True, null=True)),
                ("durP2", models.FloatField(blank=True, null=True)),
                ("ratioP2", models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="sds011",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sensor_id", models.IntegerField(blank=True, null=True)),
                ("sensor_type", models.CharField(blank=True, max_length=255)),
                ("location", models.IntegerField(blank=True, null=True)),
                ("lat", models.FloatField(blank=True, null=True)),
                ("lon", models.FloatField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(blank=True, null=True)),
                ("P1", models.FloatField(blank=True, null=True)),
                ("durP1", models.FloatField(blank=True, null=True)),
                ("ratioP1", models.FloatField(blank=True, null=True)),
                ("P2", models.FloatField(blank=True, null=True)),
                ("durP2", models.FloatField(blank=True, null=True)),
                ("ratioP2", models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
