#pylint: skip-file
from django.db import models
class bme280(models.Model):
    sensor_id = models.IntegerField(null=True, blank=True)
    sensor_type = models.CharField(max_length=255, blank=True)
    location = models.IntegerField(null=True, blank=True)
    lat = models.FloatField(null=True, blank=True)
    lon = models.FloatField(null=True, blank=True)
    timestamp = models.DateTimeField(null=True, blank=True)
    pressure = models.FloatField(null=True, blank=True)
    altitude = models.FloatField(null=True, blank=True)
    pressure_sealevel = models.FloatField(null=True, blank=True)
    temperature = models.FloatField(null=True, blank=True)
    humidity = models.FloatField(null=True, blank=True)
class bmp180(models.Model):
    sensor_id = models.IntegerField(null=True, blank=True)
    sensor_type = models.CharField(max_length=255, blank=True)
    location = models.IntegerField(null=True, blank=True)
    lat = models.FloatField(null=True, blank=True)
    lon = models.FloatField(null=True, blank=True)
    timestamp = models.DateTimeField(null=True, blank=True)
    pressure = models.FloatField(null=True, blank=True)
    altitude = models.FloatField(null=True, blank=True)
    pressure_sealevel = models.FloatField(null=True, blank=True)
    temperature = models.FloatField(null=True, blank=True)
class bmp280(models.Model):
    sensor_id = models.IntegerField(null=True, blank=True)
    sensor_type = models.CharField(max_length=255, blank=True)
    location = models.IntegerField(null=True, blank=True)
    lat = models.FloatField(null=True, blank=True)
    lon = models.FloatField(null=True, blank=True)
    timestamp = models.DateTimeField(null=True, blank=True)
    pressure = models.FloatField(null=True, blank=True)
    altitude = models.FloatField(null=True, blank=True)
    pressure_sealevel = models.FloatField(null=True, blank=True)
    temperature = models.FloatField(null=True, blank=True)
class dht22(models.Model):
    sensor_id = models.IntegerField(null=True, blank=True)
    sensor_type = models.CharField(max_length=255, blank=True)
    location = models.IntegerField(null=True, blank=True)
    lat = models.FloatField(null=True, blank=True)
    lon = models.FloatField(null=True, blank=True)
    timestamp = models.DateTimeField(null=True, blank=True)
    temperature = models.FloatField(null=True, blank=True)
    humidity = models.FloatField(null=True, blank=True)
class ds18b20(models.Model):
    sensor_id = models.IntegerField(null=True, blank=True)
    sensor_type = models.CharField(max_length=255, blank=True)
    location = models.IntegerField(null=True, blank=True)
    lat = models.FloatField(null=True, blank=True)
    lon = models.FloatField(null=True, blank=True)
    timestamp = models.DateTimeField(null=True, blank=True)
    temperature = models.FloatField(null=True, blank=True)
class hpm(models.Model):
    sensor_id = models.IntegerField(null=True, blank=True)
    sensor_type = models.CharField(max_length=255, blank=True)
    location = models.IntegerField(null=True, blank=True)
    lat = models.FloatField(null=True, blank=True)
    lon = models.FloatField(null=True, blank=True)
    timestamp = models.DateTimeField(null=True, blank=True)
    P1 = models.FloatField(null=True, blank=True)
    P2 = models.FloatField(null=True, blank=True)
class htu21d(models.Model):
    sensor_id = models.IntegerField(null=True, blank=True)
    sensor_type = models.CharField(max_length=255, blank=True)
    location = models.IntegerField(null=True, blank=True)
    lat = models.FloatField(null=True, blank=True)
    lon = models.FloatField(null=True, blank=True)
    timestamp = models.DateTimeField(null=True, blank=True)
    temperature = models.FloatField(null=True, blank=True)
    humidity = models.FloatField(null=True, blank=True)
class pms1003(models.Model):
    sensor_id = models.IntegerField(null=True, blank=True)
    sensor_type = models.CharField(max_length=255, blank=True)
    location = models.IntegerField(null=True, blank=True)
    lat = models.FloatField(null=True, blank=True)
    lon = models.FloatField(null=True, blank=True)
    timestamp = models.DateTimeField(null=True, blank=True)
    P1 = models.FloatField(null=True, blank=True)
    P2 = models.FloatField(null=True, blank=True)
    P0 = models.FloatField(null=True, blank=True)
class pms3003(models.Model):
    sensor_id = models.IntegerField(null=True, blank=True)
    sensor_type = models.CharField(max_length=255, blank=True)
    location = models.IntegerField(null=True, blank=True)
    lat = models.FloatField(null=True, blank=True)
    lon = models.FloatField(null=True, blank=True)
    timestamp = models.DateTimeField(null=True, blank=True)
    P1 = models.FloatField(null=True, blank=True)
    P2 = models.FloatField(null=True, blank=True)
    P0 = models.FloatField(null=True, blank=True)
class pms5003(models.Model):
    sensor_id = models.IntegerField(null=True, blank=True)
    sensor_type = models.CharField(max_length=255, blank=True)
    location = models.IntegerField(null=True, blank=True)
    lat = models.FloatField(null=True, blank=True)
    lon = models.FloatField(null=True, blank=True)
    timestamp = models.DateTimeField(null=True, blank=True)
    P1 = models.FloatField(null=True, blank=True)
    P2 = models.FloatField(null=True, blank=True)
    P0 = models.FloatField(null=True, blank=True)
class pms6003(models.Model):
    sensor_id = models.IntegerField(null=True, blank=True)
    sensor_type = models.CharField(max_length=255, blank=True)
    location = models.IntegerField(null=True, blank=True)
    lat = models.FloatField(null=True, blank=True)
    lon = models.FloatField(null=True, blank=True)
    timestamp = models.DateTimeField(null=True, blank=True)
    P1 = models.FloatField(null=True, blank=True)
    P2 = models.FloatField(null=True, blank=True)
    P0 = models.FloatField(null=True, blank=True)
class pms7003(models.Model):
    sensor_id = models.IntegerField(null=True, blank=True)
    sensor_type = models.CharField(max_length=255, blank=True)
    location = models.IntegerField(null=True, blank=True)
    lat = models.FloatField(null=True, blank=True)
    lon = models.FloatField(null=True, blank=True)
    timestamp = models.DateTimeField(null=True, blank=True)
    P1 = models.FloatField(null=True, blank=True)
    P2 = models.FloatField(null=True, blank=True)
    P0 = models.FloatField(null=True, blank=True)
class ppd42ns(models.Model):
    sensor_id = models.IntegerField(null=True, blank=True)
    sensor_type = models.CharField(max_length=255, blank=True)
    location = models.IntegerField(null=True, blank=True)
    lat = models.FloatField(null=True, blank=True)
    lon = models.FloatField(null=True, blank=True)
    timestamp = models.DateTimeField(null=True, blank=True)
    P1 = models.FloatField(null=True, blank=True)
    durP1 = models.FloatField(null=True, blank=True)
    ratioP1 = models.FloatField(null=True, blank=True)
    P2 = models.FloatField(null=True, blank=True)
    durP2 = models.FloatField(null=True, blank=True)
    ratioP2 = models.FloatField(null=True, blank=True)
class sds011(models.Model):
    sensor_id = models.IntegerField(null=True, blank=True)
    sensor_type = models.CharField(max_length=255, blank=True)
    location = models.IntegerField(null=True, blank=True)
    lat = models.FloatField(null=True, blank=True)
    lon = models.FloatField(null=True, blank=True)
    timestamp = models.DateTimeField(null=True, blank=True)
    P1 = models.FloatField(null=True, blank=True)
    durP1 = models.FloatField(null=True, blank=True)
    ratioP1 = models.FloatField(null=True, blank=True)
    P2 = models.FloatField(null=True, blank=True)
    durP2 = models.FloatField(null=True, blank=True)
    ratioP2 = models.FloatField(null=True, blank=True)
